# Generated by Django 3.0.4 on 2020-03-25 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200214_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pumping',
            name='breast',
            field=models.CharField(choices=[('left breast', 'Left breast'), ('right breast', 'Right breast'), ('both breasts', 'Both breasts')], max_length=255, verbose_name='Breast'),
        ),
    ]
